// Generated by   : ImageConverter BW Online
// Generated from : oshw_logo.png
// Time generated : Thu, 11 Aug 11 20:28:44 +0200  (Server timezone: CET)
// Image Size     : 56x48 pixels
// Memory usage   : 336 bytes

#include <avr/pgmspace.h>

uint8_t bluetooth[] PROGMEM= {
0x28, 0x10, 0xfe, 0xaa, 0x44
};
