// Generated by   : ImageConverter BW Online
// Generated from : oshw_logo.png
// Time generated : Thu, 11 Aug 11 20:28:44 +0200  (Server timezone: CET)
// Image Size     : 56x48 pixels
// Memory usage   : 336 bytes

#include <avr/pgmspace.h>

uint8_t farol_off[] PROGMEM= {
0x00, 0x00, 0x00, 0x00, 0x00
};
